### PR TITLE
Mobile footer nav

### PR DESCRIPTION
**Pull request by richmccartney**
#### What's this PR do?
Adds a new mobile footer similar to the one seen on ubuntu.com

#### Where should the reviewer start?
Pull the branch down and run ```npm install``` and ```gulp build```

#### How should this be manually tested?
View any page on a small screen, scroll to the footer. Open/close the different sections. Also view the code and make sure it lints.

#### Any background context you want to provide?
_n/a_

#### What are the relevant tickets?
#16 

#### Screenshots (if appropriate)
_n/a_

#### Questions:
_n/a_

### CODE REVIEW

**Comment by grahambancroft** [comment]
I’m getting gulp build NestingDepth errors

**Comment by richmccartney** [comment]
@grahambancroft which file and line? I just ran gulp test and nothing came up.

**Comment by grahambancroft** [comment]
@richmccartney base/_footer.scss:47 [W] NestingDepth: Nesting should be no greater than 3, but was 4

**Comment by richmccartney** [comment]
@grahambancroft if you give it another go please :)

**Comment by anthonydillon** [comment]
@richmccartney please dont merge without a +1 from someone in the team

**Pull request merged**
